name: Build and Publish Docker Image
 
on:
  push:
    branches:
      - main
 
jobs:
  build-api:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tizzer1331
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: Dockerfile
          push: true
          tags: ghcr.io/tizzer1331/lotrapifrontend:latest
- name: Jenkins
        run: |
          CRUMB=$(curl -u ash:{{secrets.JENKINS_API_TOKEN}} -s 'https://jenkins.netbuildertraining.com/crumbIssuer/api/json' | grep -o '"crumb":"[^"]*"' | cut -d':' -f2 | tr -d '"')
          curl -u ash:{{secrets.JENKINS_API_TOKEN}} -H "Jenkins-Crumb: $CRUMB" -X POST 'https://jenkins.netbuildertraining.com/job/https://jenkins.netbuildertraining.com/job/Jon-deployment-pipeline/build'/build'